### ISSUE TITLE
Support for multiple spec files and folders 

### ISSUE THREAD

**Issue by soumak-witbybit** [LambdaTest/lambdatest-cypress-cli#139]
Currently, we can only add one folder destination. 

Can we add support for spec files in multiple subfolders?
```js
"run_settings": {
    "specs": "./cypress/integration/**/*.spec.ts}",
}
``` 
Or can we have an array of spec files?
```js
"run_settings": {
    "specs": ["./cypress/integration/app/*.spec.ts}", "./cypress/integration/docs/*.spec.js}"],
}
```

**Comment by japneetlambdatest** [comment]
@soumak-witbybit, you can pass comma separated list of files in `specs` key

**Comment by soumak-witbybit** [comment]
@japneetlambdatest Sorry, but I'm getting this error 
```json
"specs": ["./cypress/integration/app/*.spec.ts", "./cypress/integration/docs/*.spec.ts"],
```
![image](https://user-images.githubusercontent.com/57088898/165090179-9b757f1c-42f1-4c03-94cd-e3c33e576ef0.png)

**Comment by soumak-witbybit** [comment]
Okay you mean like this. Thanks 
```json
"specs": "./cypress/integration/app/*.spec.ts, ./cypress/integration/docs/*.spec.js"
```
