### ISSUE TITLE
Support cypress config files 

### ISSUE THREAD

**Issue by webdesignberlin** [LambdaTest/lambdatest-cypress-cli#171]
When I use the package with a recent Cypress version, I get the following errors in the Lambdatest interface:

`It looks like this is your first time using Cypress: 10.0.2

[STARTED] Task without title.
[TITLE]  Verified Cypress!       E:\lambda-node-remote-client\cypress-binary\10.0.2\Cypress
[SUCCESS]  Verified Cypress!       E:\lambda-node-remote-client\cypress-binary\10.0.2\Cypress

Opening Cypress...

There is both a cypress.config.ts and a cypress.json file at the location below:

E:\lambda-node-remote-client\xxx\project

Cypress no longer supports cypress.json, please remove it from your project.`

in the project there is a cypress.config.ts file and in the lambdatest-config.json i removed the field "cypress_config_file" because it only accepts json files.

**Comment by webdesignberlin** [comment]
If the cypress.json is missing in upload, i became:
`
{
  status: 500,
  value: {
    message: 'Error occured while batching the tests open uploads/upload-xxx/tests-xxx/cypress.json: no such file or directory'
  }
` from https://github.com/LambdaTest/lambdatest-cypress-cli/blob/master/commands/utils/uploader.js#L77

**Comment by webdesignberlin** [comment]
If i add the cypress.config.ts to ignored files,
i became the following error on lambdatest interface:
`
It looks like this is your first time using Cypress: 10.0.2

[STARTED] Task without title.
[TITLE]  Verified Cypress!       E:\lambda-node-remote-client\cypress-binary\10.0.2\Cypress
[SUCCESS]  Verified Cypress!       E:\lambda-node-remote-client\cypress-binary\10.0.2\Cypress

Opening Cypress...

There is a cypress.json file at the path: E:\lambda-node-remote-client\xxx\project

Cypress version 10.0.0 no longer supports cypress.json.

Please run cypress open to launch the migration tool to migrate to cypress.config.{js,ts,mjs,cjs}.

https://on.cypress.io/migration-guide
`

**Comment by PraveenSDET** [comment]
I'm getting pretty much the same issue when integrating Cypress 10 with Lambdatest. It expects a Cypress.json configuration file. Hope Lambdatest team comes up with an upgrade for Cypress 10 soon.

_**`Checking Lambda Config in current directory
Validating CLI
Cypress.json is not parsed, please provide a valid json
Error!! Cypress Config File does not has correct json`**_

**Comment by chuac** [comment]
Stumbled upon this issue as we were integrating LambdaTest with Cypress 10, and found that it's now working with latest `lambdatest-cypress-cli@3.0.3` and `cypress@10.11.0` with `cypress.config.ts`!

Looks like the docs agree too: https://www.lambdatest.com/support/docs/supported-cypress-versions/

**Comment by japneetlambdatest** [comment]
We we not initially supporting cypress 10 but this is supported now, If you face some issue please open a fresh issue
