### ISSUE TITLE
Typescript Support Cypress

### ISSUE THREAD

**Issue by webdesignberlin** [LambdaTest/lambdatest-cypress-cli#172]
Currently its not possible to run cypress via ts.

Fresh Example Repo: https://github.com/webdesignberlin/cypress-vue-lambda
- install lambdatest-cypress-cli global
- npm install for project
- npm run build
- start preview and run lambdatest-cypress run

Test starts and ended with following output in lambdatest interface:
`
It looks like this is your first time using Cypress: 9.0.0

[STARTED] Task without title.
[TITLE]  Verified Cypress!       E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress
[SUCCESS]  Verified Cypress!       E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress

Opening Cypress...

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.0.0                                                                          │
  │ Browser:        Custom Firefox 99                                                              │
  │ Node Version:   v14.15.4 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          1 found (cypress/e2e/example.cy.ts)                                            │
  │ Searched:       cypress\e2e\example.cy.ts                                                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  cypress/e2e/example.cy.ts                                                       (1 of 1)

Oops...we found an error preparing this test file:

  cypress\e2e\example.cy.ts

The error was:

Error: Webpack Compilation Error
./cypress/e2e/example.cy.ts
Module build failed (from E:/lambda-node-remote-client/cypress-binary/9.0.0/Cypress/resources/app/packages/server/node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at handle (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\webpack-preprocessor\dist\index.js:180:23)
    at finalCallback (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\webpack\lib\Compiler.js:257:39)
    at E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\webpack\lib\Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\tapable\lib\Hook.js:154:20)
    at E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\webpack\lib\Compiler.js:304:22
    at Compiler.emitRecords (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\webpack\lib\Compiler.js:499:39)
    at E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\webpack\lib\Compiler.js:298:10
    at E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\webpack\lib\Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\tapable\lib\Hook.js:154:20)
    at E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\webpack\lib\Compiler.js:482:27
    at E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\neo-async\async.js:2818:7
    at done (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (E:\lambda-node-remote-client\cypress-binary\9.0.0\Cypress\resources\app\packages\server\node_modules\tapable\lib\Hook.js:154:20)

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        0                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     cypress/e2e/example.cy.ts                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

====================================================================================================

  (Run Finished)

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ×  cypress/e2e/example.cy.ts                  0ms        -        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ×  1 of 1 failed (100%)                       0ms        -        -        1        -        -  

`

**Comment by japneetlambdatest** [comment]
@webdesignberlin  can you put all the dependencies present in package.json in npm_dependecnies section of lambdatest-config.json file.

**Comment by tim-vyg** [comment]
You need to add `typescript` to your `npm_dependencies` in your `lambdatest-config.json` for it to work. 

But there's a problem using typescript for the config `cypress.config.ts` file :

`Your configFile is invalid: E:\lambda-node-remote-client\cbf33c83-c0ac-4c87-b334-439927d5545c\project\cypress.config.ts
`

**Comment by japneetlambdatest** [comment]
Closing as this is fixed
