### ISSUE TITLE
Passing cypress env variables

### ISSUE THREAD

**Issue by Fensterbank** [LambdaTest/lambdatest-cypress-cli#187]
Cypress tests are mostly built around environment variables, e.g. passing the base URL with `CYPRESS_BASE_URL` or passing any environment specific values, auth data, etc.

But how can I pass these environment variables using `lambdatest-cypress-cli`?
Using `--help` I saw there is a undocumented parameter `--envs`.
I read through the code and tried this
```
LT_USERNAME=user LT_ACCESS_KEY=secret lambdatest-cypress run --envs "CYPRESS_BASE_URL=https://myapp.com,CYPRESS_AUTH_USER=foo,CYPRESS_AUTH_PWD=bar"
```
But it did not work.
There is absolutely no documentation about this, but every serious cypress test suite is dependent on environment variables... So how do I solve this?
I also found something about a `cypress-env-file` parameter in the source code, but I didn't find a single mention of this in the docs.

So what's the currently supported best practice way to pass environment variables to my cypress tests?

Thanks for help.

**Comment by asad9711** [comment]
Hello @Fensterbank ,
you can pass the environment variables to your cypress tests using either of the above 2 ways mentioned or by using `cypress.env.json` as recommended by cypress - https://docs.cypress.io/guides/guides/environment-variables#Option-1-configuration-file

The way in which you are using the `--envs` parameter is correct. I hope you are accessing the declared environment variable in your cypress test like this `Cypress.env('CYPRESS_BASE_URL')`

Attaching a sample for the same here.

**sample_test_spec.js**
```js
describe('Sample test', () => {
    it('test case - actions', () => {
      cy.visit(Cypress.env('CYPRESS_BASE_URL') + Cypress.env('ACTIONS_URL'))
      cy.wait(3000)
    })
    it('test case - window', () => {
        cy.visit(Cypress.env('CYPRESS_BASE_URL') + Cypress.env('WINDOW_URL'))
        cy.wait(3000)
    })
  })
    
 ```
  
Command to run the test, 
```bash
lambdatest-cypress run --envs "CYPRESS_BASE_URL=https://example.cypress.io/,ACTIONS_URL=commands/actions,WINDOW_URL=commands/window"
```

Also, we are modifying our docs to contain examples for the same.
In case, you face further issues, please feel free to connect to our support team.
Happy to help. Thanks

**Comment by japneetlambdatest** [comment]
Closing due to unactivity

**Comment by Fensterbank** [comment]
Thank you @asad9711 for your detailed response and sorry for the inactivity from my side.
There were some bigger changes in priority so that I lost track of that issue.

I'll test your proposals and thanks for updating the docs!
