### ISSUE TITLE
npm dependency install failure

### ISSUE THREAD

**Issue by gs-scooter** [LambdaTest/lambdatest-cypress-cli#52]
I'm attempting to run `lambdatest-cypress` on an Angular 12 project locally via un UnderPass tunnel using the latest Cypress version (8.3.0). Currently, I have one test spec defined with a simple assertion. The test succeeds as expected via Cypress CLI (`npx cypress run`). When running via `lambdatest-cypress`, the test fails on the LT dashboard every time with:
```
npm dependencies installation failed for the test

npm install from package.json failed, due to : npm WARN tar ENOENT: no such file or directory, open 'E:\lambda-node-remote-client\SOME_GUID\project\node_modules\.staging\zone.js-e8b71491\dist\zone-node.min.js'
```
followed by a ton of additional similar warnings for different libs.

Below is the config being used:
```
{
  "lambdatest_auth": {
    "username": "<name>",
    "access_key": "<key>"
  },
  "browsers": [
    {
      "browser": "Chrome",
      "platform": "Windows 10",
      "versions": ["86.0"]
    }
  ],
  "run_settings": {
    "cypress_config_file": "cypress.json",
    "build_name": "local-dev",
    "parallels": 1,
    "specs": "./cypress/integration/**/*.spec.ts",
    "ignore_files": "",
    "feature_file_suppport": false,
    "network": false,
    "npm_dependencies": {
      "cypress": "8.3.0"
    }
  },
  "tunnel_settings": {
    "tunnel": true,
    "tunnel_name": "lt-cypress-tunnel"
  }
}
```

Any ideas as to what could be causing this?

**Comment by asad9711** [comment]
@gs-scooter 
Due to the presence of some npm dependencies in `package.json` which aren't able to be installed because they are private i.e they are not publicly available on internet.
Before running user's test on our platform, we make sure to install the dependencies mentioned in users's `package.json` so that all the required/imported packages in the cypress test script are available

What to do in order to resolve this - Since you may not be requiring such private npm packages in your cypress test files, you  can remove these from `package.json` and give it a try. It should work fine.

Hope it helps. Thanks

**Comment by gs-scooter** [comment]
@asad9711 - Unfortunately, we do require those private libs since they contain shared UI components. Please confirm if I understand correctly: When running Lambdatest via a tunnel to test local development, LT is retrieving the project from localhost to install dependencies and run Cypress in its own environment. Would this be true as well when running LT/Cypress from within a CodeBuild pipeline?

If that's the case, then I'm confused as to how LT/Cypress could ever work for places that leverage their own private libs.

**Comment by asad9711** [comment]
@gs-scooter - When ran via tunnel, the test traffic i.e all http/https calls made by the test script goes via the user's local network. 
The npm dependencies installation step is a precursor to test execution and that step is independent of tunnel.
Regarding project, we make sure to make the user's project available on our machines where we run the tests and remove the project after test execution.

Regarding CodeBuild pipeline, the behaviour is same as when user runs lambatest-cypress cli from terminal.

For running tests which are actually using private npm libs in the test/spec files, we are planning to come up with a solution in the near future.

**Comment by asad9711** [comment]
Support for the same has been provided in version `2.1.9` of `lambdatest-cypress-cli`
