### ISSUE TITLE
Option to set recording arguments for Cypress Dashboard

### ISSUE THREAD

**Issue by MartinPilny** [LambdaTest/lambdatest-cypress-cli#65]
### Context
Cypress Dashboard is web app for visualisation of results of Cypress tests. For example it allows to see screenshots, video recordings or analytics of test executions.
Results to the dashboard are sent via command `cypress run --record --key <record_key>`.

### Feature request
Enable to execute command `lambdatest-cypress run --cypress-record-key <record_key>` that would sent results to the dashboard.

**Comment by Shivanshu-lambdatest** [comment]
Hi @MartinPilny, thanks for writing to us. We will look into your suggestion.

**Comment by japneetlambdatest** [comment]
@MartinPilny  you can upgrade the cli to latest version and use --cy="<options that we want to pass to cypress run command>"
E.g
lambdatest-cypress run --cy="--cypress-record-key <record_key>"
